# SPDX-FileCopyrightText: 2017 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-lb-readvertiser
  namespace: default
  labels:
    app: aws-lb-readvertiser
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-lb-readvertiser
  labels:
    app: aws-lb-readvertiser
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  resourceNames:
  - kubernetes
  verbs:
  - create
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: readvertiser
  name: aws-lb-readvertiser
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-lb-readvertiser
subjects:
- kind: ServiceAccount
  name: aws-lb-readvertiser
  namespace: default
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: aws-lb-readvertiser
  namespace: default
  labels:
    app: kubernetes
    role: controller-manager
spec:
  revisionHistoryLimit: 0
  replicas: default
  selector:
    matchLabels:
      app: aws-lb-readvertiser
  template:
    metadata:
      labels:
        app: aws-lb-readvertiser
    spec:
      serviceAccountName: aws-lb-readvertiser
      tolerations:
      - effect: NoExecute
        operator: Exists
      containers:
      - name: aws-lb-readvertiser
        image: europe-docker.pkg.dev/gardener-project/public/gardener/aws-lb-readvertiser:0.4.0
        imagePullPolicy: IfNotPresent
        args:
        - --kubeconfig=/var/lib/aws-lb-readvertiser/kubeconfig
        - --elb-dns-name=api.example.com
        - --endpoint-name=kubernetes
        - --refresh-period=5
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 20m
            memory: 20Mi
        volumeMounts:
        - name: aws-lb-readvertiser
          mountPath: /var/lib/aws-lb-readvertiser
      volumes:
      - name: aws-lb-readvertiser
        secret:
          secretName: aws-lb-readvertiser
